### ISSUE TITLE
AbstractFlowConfiguration not found

### ISSUE THREAD

**Issue by davisoski** [vakho10/spring-boot-with-webflow-and-thymeleaf-configured#2]
Hi.
I have downloaded and installed your code in my eclipse photon, but once updated this imports seems not working:
import org.springframework.webflow.config.AbstractFlowConfiguration;
import org.springframework.webflow.definition.registry.FlowDefinitionRegistry;

any idea??
Thanks for your code.

**Comment by vakho10** [comment]
@davisoski Hi, maybe it has something to do with m2e connectors? Eclipse has that kind of a problem. Try running "mvn packge" in the console and see if that works.
