### ISSUE TITLE
Fork this into thymeleaf's organization to use it as a sandbox

### ISSUE THREAD

**Issue by danielfernandez** [vakho10/spring-boot-with-webflow-and-thymeleaf-configured#3]
Hi, I'm thymeleaf's author.

Would you allow me to create a fork of this repository inside the `thymeleaf` GitHub organization so that I can use it as a base for a testing application (a `thymeleafsandbox`)? It would be very helpful for the occasional testing of Spring WebFlow integration issues…

Thanks!

**Comment by danielfernandez** [comment]
Oh and by the way, if you are OK with the fork, would you agree with applying the Apache License 2.0 to the code? That's the standard for all code in the `thymeleaf` GitHub organization.

**Comment by vakho10** [comment]
@danielfernandez Hey man, do anything you want with it :) Pretty odd to get a comment from an author though :D

**Comment by danielfernandez** [comment]
Thanks a lot!
